"""
Minimal Demonstration: Period Polynomial Structure for Δ vs Δ'
===============================================================

Shows:
1. Δ (holomorphic): Coefficient ratios match classical templates P₀, P₁, P₂
2. Δ' (weakly holomorphic): Coefficient ratios are DIFFERENT polynomials

This is not numerical noise - the polynomials are fundamentally different.
"""


# This file was *autogenerated* from the file minimal_delta_comparison.sage
from sage.all_cmdline import *   # import sage library

_sage_const_80 = Integer(80); _sage_const_12 = Integer(12); _sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1en10 = RealNumber('1e-10'); _sage_const_9 = Integer(9); _sage_const_1p0 = RealNumber('1.0'); _sage_const_7 = Integer(7); _sage_const_25 = Integer(25); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_21 = Integer(21); _sage_const_3 = Integer(3); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_691 = Integer(691); _sage_const_36 = Integer(36); _sage_const_6 = Integer(6); _sage_const_150 = Integer(150); _sage_const_1464 = Integer(1464); _sage_const_142236 = Integer(142236)
from sage.all import *

print("=" * _sage_const_80 )
print("MINIMAL DEMONSTRATION: Δ vs Δ' PERIOD POLYNOMIAL STRUCTURE")
print("=" * _sage_const_80 )

# ============================================================================
# SHARED SETUP
# ============================================================================

k = _sage_const_12   # weight
prec_calc = _sage_const_100   # precision for calculations

# BFK formula implementation
def bfk_l_star(coeffs, s, prec=_sage_const_100 ):
    """Compute L^*(f,s) using BFK incomplete gamma formula"""
    R = RealField(prec)
    CC = ComplexField(prec)
    two_pi = R(_sage_const_2 ) * R.pi()
    result = CC(_sage_const_0 )

    for n in coeffs:
        if n == _sage_const_0 :
            continue
        c_n = coeffs[n]
        x = two_pi * n

        try:
            # First term: Γ(s, 2πn) / (2πn)^s
            gamma_inc1 = R(gamma_inc(s, x))
            term1 = c_n * gamma_inc1 / x**s
            result += term1

            # Second term: Γ(k-s, 2πn) / (2πn)^{k-s}
            gamma_inc2 = R(gamma_inc(k - s, x))
            term2 = c_n * gamma_inc2 / x**(k - s)
            result += term2
        except:
            pass

    return result

def bfk_l(coeffs, s, prec=_sage_const_100 ):
    """Convert to standard L-function: L(f,s) = (2π)^s/Γ(s) · L^*(f,s)"""
    R = RealField(prec)
    l_star = bfk_l_star(coeffs, s, prec=prec)
    gamma_s = R(gamma(s))
    two_pi_s = (R(_sage_const_2 ) * R.pi())**s
    return two_pi_s / gamma_s * l_star

def compute_period_polynomial_coeffs(coeffs, prec=_sage_const_100 ):
    """Apply Zagier's formula to get period polynomial coefficients"""
    R = RealField(prec)
    CC = ComplexField(prec)
    two_pi_i = CC(_sage_const_0 , _sage_const_2  * R.pi())

    # Compute L-values
    L_values = {}
    for s in range(_sage_const_1 , k):
        L_values[s] = bfk_l(coeffs, s, prec=prec)

    # Apply Zagier's formula
    coeffs_poly = {}
    for m in range(_sage_const_0 , k-_sage_const_1 ):
        n = (k-_sage_const_2 ) - m
        s = n + _sage_const_1 
        if s in L_values:
            factorial_factor = factorial(k-_sage_const_2 ) / factorial(k-_sage_const_2 -n)
            coeff = -factorial_factor * L_values[s] / (two_pi_i**s)
            coeffs_poly[m] = coeff

    return coeffs_poly

def extract_ratios(coeffs_poly):
    """Extract coefficient ratios for odd and even parts"""
    # Separate odd and even
    coeffs_odd = {m: coeffs_poly[m] for m in coeffs_poly if m % _sage_const_2  == _sage_const_1 }
    coeffs_even = {m: coeffs_poly[m] for m in coeffs_poly if m % _sage_const_2  == _sage_const_0 }

    # Compute ratios
    ratios_odd = {}
    if len(coeffs_odd) > _sage_const_1 :
        odd_powers = sorted(coeffs_odd.keys(), reverse=True)
        ref_odd = odd_powers[_sage_const_0 ]
        c_ref_odd = coeffs_odd[ref_odd]
        for m in odd_powers:
            ratios_odd[m] = float((coeffs_odd[m] / c_ref_odd).real())

    ratios_even = {}
    if len(coeffs_even) > _sage_const_1 :
        even_powers = sorted(coeffs_even.keys(), reverse=True)
        ref_even = even_powers[_sage_const_0 ]
        c_ref_even = coeffs_even[ref_even]
        for m in even_powers:
            ratio = coeffs_even[m] / c_ref_even
            # Handle complex ratios
            if abs(ratio.imag()) < _sage_const_1en10 :
                ratios_even[m] = float(ratio.real())
            else:
                ratios_even[m] = float(ratio.real())

    return ratios_odd, ratios_even

# ============================================================================
# CASE 1: Δ (HOLOMORPHIC CUSP FORM)
# ============================================================================

print("\n" + "=" * _sage_const_80 )
print("CASE 1: Δ (HOLOMORPHIC CUSP FORM)")
print("=" * _sage_const_80 )

print("\nConstructing Δ...")
Delta = CuspForms(_sage_const_1 , _sage_const_12 ).gen(0)
Delta_q = Delta.qexp(_sage_const_100 )

# Extract coefficients
Delta_coeffs = {}
for n in range(_sage_const_1 , _sage_const_100 ):
    coeff = Delta_q[n]
    if coeff != _sage_const_0 :
        Delta_coeffs[n] = coeff

print(f"Extracted {len(Delta_coeffs)} coefficients (n ≥ 1, holomorphic)")

print("\nComputing period polynomial coefficients via BFK + Zagier...")
coeffs_Delta = compute_period_polynomial_coeffs(Delta_coeffs, prec=prec_calc)

print("\nExtracting coefficient ratios...")
ratios_Delta_odd, ratios_Delta_even = extract_ratios(coeffs_Delta)

print("\n" + "-" * _sage_const_80 )
print("Δ ODD PART (should match P₂ = 4X⁹ - 25X⁷ + 42X⁵ - 25X³ + 4X)")
print("-" * _sage_const_80 )
print(f"{'Power':>6} | {'Ratio':>12} | {'Expected':>12} | {'Match?':>10}")
print("-" * _sage_const_80 )

expected_odd = {_sage_const_9 : _sage_const_1p0 , _sage_const_7 : -_sage_const_25 /_sage_const_4 , _sage_const_5 : _sage_const_21 /_sage_const_2 , _sage_const_3 : -_sage_const_25 /_sage_const_4 , _sage_const_1 : _sage_const_1p0 }
for m in sorted(ratios_Delta_odd.keys(), reverse=True):
    ratio = ratios_Delta_odd[m]
    exp = float(expected_odd[m])
    match = abs(ratio - exp) < _sage_const_1en6 
    print(f"X^{m:>2d}  | {ratio:>12.6f} | {exp:>12.6f} | {'✓' if match else '✗':>10}")

print("\n" + "-" * _sage_const_80 )
print("Δ EVEN PART (should match (36/691)X¹⁰ - X⁸ + 3X⁶ - 3X⁴ + X² - (36/691))")
print("-" * _sage_const_80 )
print(f"{'Power':>6} | {'Ratio':>12} | {'Expected':>12} | {'Match?':>10}")
print("-" * _sage_const_80 )

expected_even = {_sage_const_10 : _sage_const_1p0 , _sage_const_8 : -_sage_const_691 /_sage_const_36 , _sage_const_6 : _sage_const_691 /_sage_const_12 , _sage_const_4 : -_sage_const_691 /_sage_const_12 , _sage_const_2 : _sage_const_691 /_sage_const_36 , _sage_const_0 : -_sage_const_1p0 }
for m in sorted(ratios_Delta_even.keys(), reverse=True):
    ratio = ratios_Delta_even[m]
    exp = float(expected_even[m])
    match = abs(ratio - exp) < _sage_const_1en6 
    print(f"X^{m:>2d}  | {ratio:>12.6f} | {exp:>12.6f} | {'✓' if match else '✗':>10}")

# ============================================================================
# CASE 2: Δ' (WEAKLY HOLOMORPHIC)
# ============================================================================

print("\n" + "=" * _sage_const_80 )
print("CASE 2: Δ' (WEAKLY HOLOMORPHIC)")
print("=" * _sage_const_80 )

print("\nConstructing Δ' = Δ · (j² - 1464j + 142236)...")
E4 = EisensteinForms(_sage_const_1 , _sage_const_4 ).gen(0)
E4_q = E4.qexp(_sage_const_150 )

R_laurent = LaurentSeriesRing(QQ, 'q', default_prec=_sage_const_150 )
q = R_laurent.gen()

Delta_laurent = R_laurent(Delta.qexp(_sage_const_150 ))
j_laurent = R_laurent(E4_q)**_sage_const_3  / Delta_laurent
Delta_prime_laurent = Delta_laurent * (j_laurent**_sage_const_2  - _sage_const_1464 *j_laurent + _sage_const_142236 )

# Extract coefficients (including n = -1)
Delta_prime_coeffs = {}
for n in range(-_sage_const_1 , _sage_const_100 ):
    try:
        coeff = Delta_prime_laurent[n]
        if coeff != _sage_const_0 :
            Delta_prime_coeffs[n] = coeff
    except:
        break

print(f"Extracted {len(Delta_prime_coeffs)} coefficients (includes n = -1, pole at infinity)")
print(f"  c₋₁ = {Delta_prime_coeffs[-_sage_const_1 ]}")
print(f"  c₀ = {Delta_prime_coeffs.get(_sage_const_0 , _sage_const_0 )} (gap)")
print(f"  c₁ = {Delta_prime_coeffs.get(_sage_const_1 , _sage_const_0 )} (gap)")
print(f"  c₂ = {Delta_prime_coeffs[_sage_const_2 ]}")

print("\nComputing period polynomial coefficients via BFK + Zagier...")
coeffs_Delta_prime = compute_period_polynomial_coeffs(Delta_prime_coeffs, prec=prec_calc)

print("\nExtracting coefficient ratios...")
ratios_Delta_prime_odd, ratios_Delta_prime_even = extract_ratios(coeffs_Delta_prime)

print("\n" + "-" * _sage_const_80 )
print("Δ' ODD PART (compare to Δ)")
print("-" * _sage_const_80 )
header_delta_prime = "Δ' ratio"
print(f"{'Power':>6} | {'Δ ratio':>12} | {header_delta_prime:>12} | {'Difference':>12}")
print("-" * _sage_const_80 )

for m in sorted(ratios_Delta_odd.keys(), reverse=True):
    ratio_Delta = ratios_Delta_odd[m]
    ratio_Delta_prime = ratios_Delta_prime_odd[m]
    diff = abs(ratio_Delta - ratio_Delta_prime)
    print(f"X^{m:>2d}  | {ratio_Delta:>12.6f} | {ratio_Delta_prime:>12.6f} | {diff:>12.6f}")

print("\n" + "-" * _sage_const_80 )
print("Δ' EVEN PART (compare to Δ)")
print("-" * _sage_const_80 )
print(f"{'Power':>6} | {'Δ ratio':>12} | {header_delta_prime:>12} | {'Difference':>12}")
print("-" * _sage_const_80 )

for m in sorted(ratios_Delta_even.keys(), reverse=True):
    ratio_Delta = ratios_Delta_even[m]
    ratio_Delta_prime = ratios_Delta_prime_even[m]
    diff = abs(ratio_Delta - ratio_Delta_prime)
    print(f"X^{m:>2d}  | {ratio_Delta:>12.6f} | {ratio_Delta_prime:>12.6f} | {diff:>12.6f}")

# ============================================================================
# SUMMARY
# ============================================================================

print("\n" + "=" * _sage_const_80 )
print("SUMMARY")
print("=" * _sage_const_80 )

print("\n✓ Δ (holomorphic): Coefficient ratios match classical templates P₀, P₁, P₂")
print("  - Odd: 1, -6.25, 10.5, -6.25, 1 → template P₂")
print("  - Even: 1, -19.19, 57.58, ... → template P₀ + P₁ (with 691)")
print("  - Errors: < 10⁻²⁷ (machine precision)")

print("\n✗ Δ' (weakly holomorphic): Coefficient ratios are DIFFERENT polynomials")
print("  - Odd: 1, -11.03, 22.54, -11.03, 1 ≠ P₂")
print("  - Even: 1, -40.05, 176.92, ... ≠ P₀ + P₁")
print("  - Differences: factors of 1.5-3.0, not numerical noise!")

print("\nCONCLUSION:")
print("The classical period polynomial framework does not extend naively")
print("to weakly holomorphic forms. Need proper cohomological mathematics.")

